// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entitypricehistory"
)

// EntityPriceHistory is the model entity for the EntityPriceHistory schema.
type EntityPriceHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	EntityID uuid.UUID `json:"entity_id,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// MarketLow holds the value of the "market_low" field.
	MarketLow float64 `json:"market_low,omitempty"`
	// MarketMid holds the value of the "market_mid" field.
	MarketMid float64 `json:"market_mid,omitempty"`
	// MarketHigh holds the value of the "market_high" field.
	MarketHigh float64 `json:"market_high,omitempty"`
	// DirectLow holds the value of the "direct_low" field.
	DirectLow float64 `json:"direct_low,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID string `json:"source_id,omitempty"`
	// RecordedAt holds the value of the "recorded_at" field.
	RecordedAt time.Time `json:"recorded_at,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EntityPriceHistoryQuery when eager-loading is set.
	Edges        EntityPriceHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EntityPriceHistoryEdges holds the relations/edges for other nodes in the graph.
type EntityPriceHistoryEdges struct {
	// Entity holds the value of the entity edge.
	Entity *Entity `json:"entity,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EntityOrErr returns the Entity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntityPriceHistoryEdges) EntityOrErr() (*Entity, error) {
	if e.Entity != nil {
		return e.Entity, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: entity.Label}
	}
	return nil, &NotLoadedError{edge: "entity"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EntityPriceHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entitypricehistory.FieldPrice, entitypricehistory.FieldMarketLow, entitypricehistory.FieldMarketMid, entitypricehistory.FieldMarketHigh, entitypricehistory.FieldDirectLow:
			values[i] = new(sql.NullFloat64)
		case entitypricehistory.FieldSource, entitypricehistory.FieldSourceID, entitypricehistory.FieldNotes:
			values[i] = new(sql.NullString)
		case entitypricehistory.FieldCreatedAt, entitypricehistory.FieldUpdatedAt, entitypricehistory.FieldRecordedAt:
			values[i] = new(sql.NullTime)
		case entitypricehistory.FieldID, entitypricehistory.FieldEntityID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EntityPriceHistory fields.
func (_m *EntityPriceHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entitypricehistory.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case entitypricehistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case entitypricehistory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case entitypricehistory.FieldEntityID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value != nil {
				_m.EntityID = *value
			}
		case entitypricehistory.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case entitypricehistory.FieldMarketLow:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field market_low", values[i])
			} else if value.Valid {
				_m.MarketLow = value.Float64
			}
		case entitypricehistory.FieldMarketMid:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field market_mid", values[i])
			} else if value.Valid {
				_m.MarketMid = value.Float64
			}
		case entitypricehistory.FieldMarketHigh:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field market_high", values[i])
			} else if value.Valid {
				_m.MarketHigh = value.Float64
			}
		case entitypricehistory.FieldDirectLow:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field direct_low", values[i])
			} else if value.Valid {
				_m.DirectLow = value.Float64
			}
		case entitypricehistory.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case entitypricehistory.FieldSourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.String
			}
		case entitypricehistory.FieldRecordedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field recorded_at", values[i])
			} else if value.Valid {
				_m.RecordedAt = value.Time
			}
		case entitypricehistory.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EntityPriceHistory.
// This includes values selected through modifiers, order, etc.
func (_m *EntityPriceHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEntity queries the "entity" edge of the EntityPriceHistory entity.
func (_m *EntityPriceHistory) QueryEntity() *EntityQuery {
	return NewEntityPriceHistoryClient(_m.config).QueryEntity(_m)
}

// Update returns a builder for updating this EntityPriceHistory.
// Note that you need to call EntityPriceHistory.Unwrap() before calling this method if this EntityPriceHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EntityPriceHistory) Update() *EntityPriceHistoryUpdateOne {
	return NewEntityPriceHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EntityPriceHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EntityPriceHistory) Unwrap() *EntityPriceHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EntityPriceHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EntityPriceHistory) String() string {
	var builder strings.Builder
	builder.WriteString("EntityPriceHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("entity_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntityID))
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("market_low=")
	builder.WriteString(fmt.Sprintf("%v", _m.MarketLow))
	builder.WriteString(", ")
	builder.WriteString("market_mid=")
	builder.WriteString(fmt.Sprintf("%v", _m.MarketMid))
	builder.WriteString(", ")
	builder.WriteString("market_high=")
	builder.WriteString(fmt.Sprintf("%v", _m.MarketHigh))
	builder.WriteString(", ")
	builder.WriteString("direct_low=")
	builder.WriteString(fmt.Sprintf("%v", _m.DirectLow))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(_m.SourceID)
	builder.WriteString(", ")
	builder.WriteString("recorded_at=")
	builder.WriteString(_m.RecordedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteByte(')')
	return builder.String()
}

// EntityPriceHistories is a parsable slice of EntityPriceHistory.
type EntityPriceHistories []*EntityPriceHistory
