// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entitypricehistory"
)

// EntityPriceHistoryCreate is the builder for creating a EntityPriceHistory entity.
type EntityPriceHistoryCreate struct {
	config
	mutation *EntityPriceHistoryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *EntityPriceHistoryCreate) SetCreatedAt(v time.Time) *EntityPriceHistoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EntityPriceHistoryCreate) SetNillableCreatedAt(v *time.Time) *EntityPriceHistoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EntityPriceHistoryCreate) SetUpdatedAt(v time.Time) *EntityPriceHistoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EntityPriceHistoryCreate) SetNillableUpdatedAt(v *time.Time) *EntityPriceHistoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEntityID sets the "entity_id" field.
func (_c *EntityPriceHistoryCreate) SetEntityID(v uuid.UUID) *EntityPriceHistoryCreate {
	_c.mutation.SetEntityID(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *EntityPriceHistoryCreate) SetPrice(v float64) *EntityPriceHistoryCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *EntityPriceHistoryCreate) SetNillablePrice(v *float64) *EntityPriceHistoryCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetMarketLow sets the "market_low" field.
func (_c *EntityPriceHistoryCreate) SetMarketLow(v float64) *EntityPriceHistoryCreate {
	_c.mutation.SetMarketLow(v)
	return _c
}

// SetNillableMarketLow sets the "market_low" field if the given value is not nil.
func (_c *EntityPriceHistoryCreate) SetNillableMarketLow(v *float64) *EntityPriceHistoryCreate {
	if v != nil {
		_c.SetMarketLow(*v)
	}
	return _c
}

// SetMarketMid sets the "market_mid" field.
func (_c *EntityPriceHistoryCreate) SetMarketMid(v float64) *EntityPriceHistoryCreate {
	_c.mutation.SetMarketMid(v)
	return _c
}

// SetNillableMarketMid sets the "market_mid" field if the given value is not nil.
func (_c *EntityPriceHistoryCreate) SetNillableMarketMid(v *float64) *EntityPriceHistoryCreate {
	if v != nil {
		_c.SetMarketMid(*v)
	}
	return _c
}

// SetMarketHigh sets the "market_high" field.
func (_c *EntityPriceHistoryCreate) SetMarketHigh(v float64) *EntityPriceHistoryCreate {
	_c.mutation.SetMarketHigh(v)
	return _c
}

// SetNillableMarketHigh sets the "market_high" field if the given value is not nil.
func (_c *EntityPriceHistoryCreate) SetNillableMarketHigh(v *float64) *EntityPriceHistoryCreate {
	if v != nil {
		_c.SetMarketHigh(*v)
	}
	return _c
}

// SetDirectLow sets the "direct_low" field.
func (_c *EntityPriceHistoryCreate) SetDirectLow(v float64) *EntityPriceHistoryCreate {
	_c.mutation.SetDirectLow(v)
	return _c
}

// SetNillableDirectLow sets the "direct_low" field if the given value is not nil.
func (_c *EntityPriceHistoryCreate) SetNillableDirectLow(v *float64) *EntityPriceHistoryCreate {
	if v != nil {
		_c.SetDirectLow(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *EntityPriceHistoryCreate) SetSource(v string) *EntityPriceHistoryCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *EntityPriceHistoryCreate) SetNillableSource(v *string) *EntityPriceHistoryCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *EntityPriceHistoryCreate) SetSourceID(v string) *EntityPriceHistoryCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_c *EntityPriceHistoryCreate) SetNillableSourceID(v *string) *EntityPriceHistoryCreate {
	if v != nil {
		_c.SetSourceID(*v)
	}
	return _c
}

// SetRecordedAt sets the "recorded_at" field.
func (_c *EntityPriceHistoryCreate) SetRecordedAt(v time.Time) *EntityPriceHistoryCreate {
	_c.mutation.SetRecordedAt(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *EntityPriceHistoryCreate) SetNotes(v string) *EntityPriceHistoryCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *EntityPriceHistoryCreate) SetNillableNotes(v *string) *EntityPriceHistoryCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EntityPriceHistoryCreate) SetID(v uuid.UUID) *EntityPriceHistoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EntityPriceHistoryCreate) SetNillableID(v *uuid.UUID) *EntityPriceHistoryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_c *EntityPriceHistoryCreate) SetEntity(v *Entity) *EntityPriceHistoryCreate {
	return _c.SetEntityID(v.ID)
}

// Mutation returns the EntityPriceHistoryMutation object of the builder.
func (_c *EntityPriceHistoryCreate) Mutation() *EntityPriceHistoryMutation {
	return _c.mutation
}

// Save creates the EntityPriceHistory in the database.
func (_c *EntityPriceHistoryCreate) Save(ctx context.Context) (*EntityPriceHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EntityPriceHistoryCreate) SaveX(ctx context.Context) *EntityPriceHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityPriceHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityPriceHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EntityPriceHistoryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := entitypricehistory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := entitypricehistory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Price(); !ok {
		v := entitypricehistory.DefaultPrice
		_c.mutation.SetPrice(v)
	}
	if _, ok := _c.mutation.MarketLow(); !ok {
		v := entitypricehistory.DefaultMarketLow
		_c.mutation.SetMarketLow(v)
	}
	if _, ok := _c.mutation.MarketMid(); !ok {
		v := entitypricehistory.DefaultMarketMid
		_c.mutation.SetMarketMid(v)
	}
	if _, ok := _c.mutation.MarketHigh(); !ok {
		v := entitypricehistory.DefaultMarketHigh
		_c.mutation.SetMarketHigh(v)
	}
	if _, ok := _c.mutation.DirectLow(); !ok {
		v := entitypricehistory.DefaultDirectLow
		_c.mutation.SetDirectLow(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := entitypricehistory.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := entitypricehistory.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EntityPriceHistoryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EntityPriceHistory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EntityPriceHistory.updated_at"`)}
	}
	if _, ok := _c.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "EntityPriceHistory.entity_id"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "EntityPriceHistory.price"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "EntityPriceHistory.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := entitypricehistory.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "EntityPriceHistory.source": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SourceID(); ok {
		if err := entitypricehistory.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "EntityPriceHistory.source_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecordedAt(); !ok {
		return &ValidationError{Name: "recorded_at", err: errors.New(`ent: missing required field "EntityPriceHistory.recorded_at"`)}
	}
	if v, ok := _c.mutation.Notes(); ok {
		if err := entitypricehistory.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "EntityPriceHistory.notes": %w`, err)}
		}
	}
	if len(_c.mutation.EntityIDs()) == 0 {
		return &ValidationError{Name: "entity", err: errors.New(`ent: missing required edge "EntityPriceHistory.entity"`)}
	}
	return nil
}

func (_c *EntityPriceHistoryCreate) sqlSave(ctx context.Context) (*EntityPriceHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EntityPriceHistoryCreate) createSpec() (*EntityPriceHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &EntityPriceHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entitypricehistory.Table, sqlgraph.NewFieldSpec(entitypricehistory.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(entitypricehistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(entitypricehistory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(entitypricehistory.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.MarketLow(); ok {
		_spec.SetField(entitypricehistory.FieldMarketLow, field.TypeFloat64, value)
		_node.MarketLow = value
	}
	if value, ok := _c.mutation.MarketMid(); ok {
		_spec.SetField(entitypricehistory.FieldMarketMid, field.TypeFloat64, value)
		_node.MarketMid = value
	}
	if value, ok := _c.mutation.MarketHigh(); ok {
		_spec.SetField(entitypricehistory.FieldMarketHigh, field.TypeFloat64, value)
		_node.MarketHigh = value
	}
	if value, ok := _c.mutation.DirectLow(); ok {
		_spec.SetField(entitypricehistory.FieldDirectLow, field.TypeFloat64, value)
		_node.DirectLow = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(entitypricehistory.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(entitypricehistory.FieldSourceID, field.TypeString, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.RecordedAt(); ok {
		_spec.SetField(entitypricehistory.FieldRecordedAt, field.TypeTime, value)
		_node.RecordedAt = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(entitypricehistory.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if nodes := _c.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitypricehistory.EntityTable,
			Columns: []string{entitypricehistory.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EntityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EntityPriceHistoryCreateBulk is the builder for creating many EntityPriceHistory entities in bulk.
type EntityPriceHistoryCreateBulk struct {
	config
	err      error
	builders []*EntityPriceHistoryCreate
}

// Save creates the EntityPriceHistory entities in the database.
func (_c *EntityPriceHistoryCreateBulk) Save(ctx context.Context) ([]*EntityPriceHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EntityPriceHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntityPriceHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EntityPriceHistoryCreateBulk) SaveX(ctx context.Context) []*EntityPriceHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityPriceHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityPriceHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
