// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entitypricehistory"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// EntityPriceHistoryDelete is the builder for deleting a EntityPriceHistory entity.
type EntityPriceHistoryDelete struct {
	config
	hooks    []Hook
	mutation *EntityPriceHistoryMutation
}

// Where appends a list predicates to the EntityPriceHistoryDelete builder.
func (_d *EntityPriceHistoryDelete) Where(ps ...predicate.EntityPriceHistory) *EntityPriceHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EntityPriceHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EntityPriceHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EntityPriceHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(entitypricehistory.Table, sqlgraph.NewFieldSpec(entitypricehistory.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EntityPriceHistoryDeleteOne is the builder for deleting a single EntityPriceHistory entity.
type EntityPriceHistoryDeleteOne struct {
	_d *EntityPriceHistoryDelete
}

// Where appends a list predicates to the EntityPriceHistoryDelete builder.
func (_d *EntityPriceHistoryDeleteOne) Where(ps ...predicate.EntityPriceHistory) *EntityPriceHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EntityPriceHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{entitypricehistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EntityPriceHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
