// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entitypricehistory"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// EntityPriceHistoryUpdate is the builder for updating EntityPriceHistory entities.
type EntityPriceHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *EntityPriceHistoryMutation
}

// Where appends a list predicates to the EntityPriceHistoryUpdate builder.
func (_u *EntityPriceHistoryUpdate) Where(ps ...predicate.EntityPriceHistory) *EntityPriceHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntityPriceHistoryUpdate) SetUpdatedAt(v time.Time) *EntityPriceHistoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *EntityPriceHistoryUpdate) SetEntityID(v uuid.UUID) *EntityPriceHistoryUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdate) SetNillableEntityID(v *uuid.UUID) *EntityPriceHistoryUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *EntityPriceHistoryUpdate) SetPrice(v float64) *EntityPriceHistoryUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdate) SetNillablePrice(v *float64) *EntityPriceHistoryUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *EntityPriceHistoryUpdate) AddPrice(v float64) *EntityPriceHistoryUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetMarketLow sets the "market_low" field.
func (_u *EntityPriceHistoryUpdate) SetMarketLow(v float64) *EntityPriceHistoryUpdate {
	_u.mutation.ResetMarketLow()
	_u.mutation.SetMarketLow(v)
	return _u
}

// SetNillableMarketLow sets the "market_low" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdate) SetNillableMarketLow(v *float64) *EntityPriceHistoryUpdate {
	if v != nil {
		_u.SetMarketLow(*v)
	}
	return _u
}

// AddMarketLow adds value to the "market_low" field.
func (_u *EntityPriceHistoryUpdate) AddMarketLow(v float64) *EntityPriceHistoryUpdate {
	_u.mutation.AddMarketLow(v)
	return _u
}

// ClearMarketLow clears the value of the "market_low" field.
func (_u *EntityPriceHistoryUpdate) ClearMarketLow() *EntityPriceHistoryUpdate {
	_u.mutation.ClearMarketLow()
	return _u
}

// SetMarketMid sets the "market_mid" field.
func (_u *EntityPriceHistoryUpdate) SetMarketMid(v float64) *EntityPriceHistoryUpdate {
	_u.mutation.ResetMarketMid()
	_u.mutation.SetMarketMid(v)
	return _u
}

// SetNillableMarketMid sets the "market_mid" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdate) SetNillableMarketMid(v *float64) *EntityPriceHistoryUpdate {
	if v != nil {
		_u.SetMarketMid(*v)
	}
	return _u
}

// AddMarketMid adds value to the "market_mid" field.
func (_u *EntityPriceHistoryUpdate) AddMarketMid(v float64) *EntityPriceHistoryUpdate {
	_u.mutation.AddMarketMid(v)
	return _u
}

// ClearMarketMid clears the value of the "market_mid" field.
func (_u *EntityPriceHistoryUpdate) ClearMarketMid() *EntityPriceHistoryUpdate {
	_u.mutation.ClearMarketMid()
	return _u
}

// SetMarketHigh sets the "market_high" field.
func (_u *EntityPriceHistoryUpdate) SetMarketHigh(v float64) *EntityPriceHistoryUpdate {
	_u.mutation.ResetMarketHigh()
	_u.mutation.SetMarketHigh(v)
	return _u
}

// SetNillableMarketHigh sets the "market_high" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdate) SetNillableMarketHigh(v *float64) *EntityPriceHistoryUpdate {
	if v != nil {
		_u.SetMarketHigh(*v)
	}
	return _u
}

// AddMarketHigh adds value to the "market_high" field.
func (_u *EntityPriceHistoryUpdate) AddMarketHigh(v float64) *EntityPriceHistoryUpdate {
	_u.mutation.AddMarketHigh(v)
	return _u
}

// ClearMarketHigh clears the value of the "market_high" field.
func (_u *EntityPriceHistoryUpdate) ClearMarketHigh() *EntityPriceHistoryUpdate {
	_u.mutation.ClearMarketHigh()
	return _u
}

// SetDirectLow sets the "direct_low" field.
func (_u *EntityPriceHistoryUpdate) SetDirectLow(v float64) *EntityPriceHistoryUpdate {
	_u.mutation.ResetDirectLow()
	_u.mutation.SetDirectLow(v)
	return _u
}

// SetNillableDirectLow sets the "direct_low" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdate) SetNillableDirectLow(v *float64) *EntityPriceHistoryUpdate {
	if v != nil {
		_u.SetDirectLow(*v)
	}
	return _u
}

// AddDirectLow adds value to the "direct_low" field.
func (_u *EntityPriceHistoryUpdate) AddDirectLow(v float64) *EntityPriceHistoryUpdate {
	_u.mutation.AddDirectLow(v)
	return _u
}

// ClearDirectLow clears the value of the "direct_low" field.
func (_u *EntityPriceHistoryUpdate) ClearDirectLow() *EntityPriceHistoryUpdate {
	_u.mutation.ClearDirectLow()
	return _u
}

// SetSource sets the "source" field.
func (_u *EntityPriceHistoryUpdate) SetSource(v string) *EntityPriceHistoryUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdate) SetNillableSource(v *string) *EntityPriceHistoryUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *EntityPriceHistoryUpdate) SetSourceID(v string) *EntityPriceHistoryUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdate) SetNillableSourceID(v *string) *EntityPriceHistoryUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *EntityPriceHistoryUpdate) ClearSourceID() *EntityPriceHistoryUpdate {
	_u.mutation.ClearSourceID()
	return _u
}

// SetRecordedAt sets the "recorded_at" field.
func (_u *EntityPriceHistoryUpdate) SetRecordedAt(v time.Time) *EntityPriceHistoryUpdate {
	_u.mutation.SetRecordedAt(v)
	return _u
}

// SetNillableRecordedAt sets the "recorded_at" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdate) SetNillableRecordedAt(v *time.Time) *EntityPriceHistoryUpdate {
	if v != nil {
		_u.SetRecordedAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *EntityPriceHistoryUpdate) SetNotes(v string) *EntityPriceHistoryUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdate) SetNillableNotes(v *string) *EntityPriceHistoryUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *EntityPriceHistoryUpdate) ClearNotes() *EntityPriceHistoryUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_u *EntityPriceHistoryUpdate) SetEntity(v *Entity) *EntityPriceHistoryUpdate {
	return _u.SetEntityID(v.ID)
}

// Mutation returns the EntityPriceHistoryMutation object of the builder.
func (_u *EntityPriceHistoryUpdate) Mutation() *EntityPriceHistoryMutation {
	return _u.mutation
}

// ClearEntity clears the "entity" edge to the Entity entity.
func (_u *EntityPriceHistoryUpdate) ClearEntity() *EntityPriceHistoryUpdate {
	_u.mutation.ClearEntity()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntityPriceHistoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntityPriceHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntityPriceHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntityPriceHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntityPriceHistoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entitypricehistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntityPriceHistoryUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := entitypricehistory.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "EntityPriceHistory.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceID(); ok {
		if err := entitypricehistory.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "EntityPriceHistory.source_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Notes(); ok {
		if err := entitypricehistory.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "EntityPriceHistory.notes": %w`, err)}
		}
	}
	if _u.mutation.EntityCleared() && len(_u.mutation.EntityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityPriceHistory.entity"`)
	}
	return nil
}

func (_u *EntityPriceHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entitypricehistory.Table, entitypricehistory.Columns, sqlgraph.NewFieldSpec(entitypricehistory.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entitypricehistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(entitypricehistory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(entitypricehistory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MarketLow(); ok {
		_spec.SetField(entitypricehistory.FieldMarketLow, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMarketLow(); ok {
		_spec.AddField(entitypricehistory.FieldMarketLow, field.TypeFloat64, value)
	}
	if _u.mutation.MarketLowCleared() {
		_spec.ClearField(entitypricehistory.FieldMarketLow, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MarketMid(); ok {
		_spec.SetField(entitypricehistory.FieldMarketMid, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMarketMid(); ok {
		_spec.AddField(entitypricehistory.FieldMarketMid, field.TypeFloat64, value)
	}
	if _u.mutation.MarketMidCleared() {
		_spec.ClearField(entitypricehistory.FieldMarketMid, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MarketHigh(); ok {
		_spec.SetField(entitypricehistory.FieldMarketHigh, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMarketHigh(); ok {
		_spec.AddField(entitypricehistory.FieldMarketHigh, field.TypeFloat64, value)
	}
	if _u.mutation.MarketHighCleared() {
		_spec.ClearField(entitypricehistory.FieldMarketHigh, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DirectLow(); ok {
		_spec.SetField(entitypricehistory.FieldDirectLow, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDirectLow(); ok {
		_spec.AddField(entitypricehistory.FieldDirectLow, field.TypeFloat64, value)
	}
	if _u.mutation.DirectLowCleared() {
		_spec.ClearField(entitypricehistory.FieldDirectLow, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(entitypricehistory.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(entitypricehistory.FieldSourceID, field.TypeString, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(entitypricehistory.FieldSourceID, field.TypeString)
	}
	if value, ok := _u.mutation.RecordedAt(); ok {
		_spec.SetField(entitypricehistory.FieldRecordedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(entitypricehistory.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(entitypricehistory.FieldNotes, field.TypeString)
	}
	if _u.mutation.EntityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitypricehistory.EntityTable,
			Columns: []string{entitypricehistory.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitypricehistory.EntityTable,
			Columns: []string{entitypricehistory.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitypricehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntityPriceHistoryUpdateOne is the builder for updating a single EntityPriceHistory entity.
type EntityPriceHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntityPriceHistoryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntityPriceHistoryUpdateOne) SetUpdatedAt(v time.Time) *EntityPriceHistoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *EntityPriceHistoryUpdateOne) SetEntityID(v uuid.UUID) *EntityPriceHistoryUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdateOne) SetNillableEntityID(v *uuid.UUID) *EntityPriceHistoryUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *EntityPriceHistoryUpdateOne) SetPrice(v float64) *EntityPriceHistoryUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdateOne) SetNillablePrice(v *float64) *EntityPriceHistoryUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *EntityPriceHistoryUpdateOne) AddPrice(v float64) *EntityPriceHistoryUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetMarketLow sets the "market_low" field.
func (_u *EntityPriceHistoryUpdateOne) SetMarketLow(v float64) *EntityPriceHistoryUpdateOne {
	_u.mutation.ResetMarketLow()
	_u.mutation.SetMarketLow(v)
	return _u
}

// SetNillableMarketLow sets the "market_low" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdateOne) SetNillableMarketLow(v *float64) *EntityPriceHistoryUpdateOne {
	if v != nil {
		_u.SetMarketLow(*v)
	}
	return _u
}

// AddMarketLow adds value to the "market_low" field.
func (_u *EntityPriceHistoryUpdateOne) AddMarketLow(v float64) *EntityPriceHistoryUpdateOne {
	_u.mutation.AddMarketLow(v)
	return _u
}

// ClearMarketLow clears the value of the "market_low" field.
func (_u *EntityPriceHistoryUpdateOne) ClearMarketLow() *EntityPriceHistoryUpdateOne {
	_u.mutation.ClearMarketLow()
	return _u
}

// SetMarketMid sets the "market_mid" field.
func (_u *EntityPriceHistoryUpdateOne) SetMarketMid(v float64) *EntityPriceHistoryUpdateOne {
	_u.mutation.ResetMarketMid()
	_u.mutation.SetMarketMid(v)
	return _u
}

// SetNillableMarketMid sets the "market_mid" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdateOne) SetNillableMarketMid(v *float64) *EntityPriceHistoryUpdateOne {
	if v != nil {
		_u.SetMarketMid(*v)
	}
	return _u
}

// AddMarketMid adds value to the "market_mid" field.
func (_u *EntityPriceHistoryUpdateOne) AddMarketMid(v float64) *EntityPriceHistoryUpdateOne {
	_u.mutation.AddMarketMid(v)
	return _u
}

// ClearMarketMid clears the value of the "market_mid" field.
func (_u *EntityPriceHistoryUpdateOne) ClearMarketMid() *EntityPriceHistoryUpdateOne {
	_u.mutation.ClearMarketMid()
	return _u
}

// SetMarketHigh sets the "market_high" field.
func (_u *EntityPriceHistoryUpdateOne) SetMarketHigh(v float64) *EntityPriceHistoryUpdateOne {
	_u.mutation.ResetMarketHigh()
	_u.mutation.SetMarketHigh(v)
	return _u
}

// SetNillableMarketHigh sets the "market_high" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdateOne) SetNillableMarketHigh(v *float64) *EntityPriceHistoryUpdateOne {
	if v != nil {
		_u.SetMarketHigh(*v)
	}
	return _u
}

// AddMarketHigh adds value to the "market_high" field.
func (_u *EntityPriceHistoryUpdateOne) AddMarketHigh(v float64) *EntityPriceHistoryUpdateOne {
	_u.mutation.AddMarketHigh(v)
	return _u
}

// ClearMarketHigh clears the value of the "market_high" field.
func (_u *EntityPriceHistoryUpdateOne) ClearMarketHigh() *EntityPriceHistoryUpdateOne {
	_u.mutation.ClearMarketHigh()
	return _u
}

// SetDirectLow sets the "direct_low" field.
func (_u *EntityPriceHistoryUpdateOne) SetDirectLow(v float64) *EntityPriceHistoryUpdateOne {
	_u.mutation.ResetDirectLow()
	_u.mutation.SetDirectLow(v)
	return _u
}

// SetNillableDirectLow sets the "direct_low" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdateOne) SetNillableDirectLow(v *float64) *EntityPriceHistoryUpdateOne {
	if v != nil {
		_u.SetDirectLow(*v)
	}
	return _u
}

// AddDirectLow adds value to the "direct_low" field.
func (_u *EntityPriceHistoryUpdateOne) AddDirectLow(v float64) *EntityPriceHistoryUpdateOne {
	_u.mutation.AddDirectLow(v)
	return _u
}

// ClearDirectLow clears the value of the "direct_low" field.
func (_u *EntityPriceHistoryUpdateOne) ClearDirectLow() *EntityPriceHistoryUpdateOne {
	_u.mutation.ClearDirectLow()
	return _u
}

// SetSource sets the "source" field.
func (_u *EntityPriceHistoryUpdateOne) SetSource(v string) *EntityPriceHistoryUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdateOne) SetNillableSource(v *string) *EntityPriceHistoryUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *EntityPriceHistoryUpdateOne) SetSourceID(v string) *EntityPriceHistoryUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdateOne) SetNillableSourceID(v *string) *EntityPriceHistoryUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *EntityPriceHistoryUpdateOne) ClearSourceID() *EntityPriceHistoryUpdateOne {
	_u.mutation.ClearSourceID()
	return _u
}

// SetRecordedAt sets the "recorded_at" field.
func (_u *EntityPriceHistoryUpdateOne) SetRecordedAt(v time.Time) *EntityPriceHistoryUpdateOne {
	_u.mutation.SetRecordedAt(v)
	return _u
}

// SetNillableRecordedAt sets the "recorded_at" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdateOne) SetNillableRecordedAt(v *time.Time) *EntityPriceHistoryUpdateOne {
	if v != nil {
		_u.SetRecordedAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *EntityPriceHistoryUpdateOne) SetNotes(v string) *EntityPriceHistoryUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *EntityPriceHistoryUpdateOne) SetNillableNotes(v *string) *EntityPriceHistoryUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *EntityPriceHistoryUpdateOne) ClearNotes() *EntityPriceHistoryUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_u *EntityPriceHistoryUpdateOne) SetEntity(v *Entity) *EntityPriceHistoryUpdateOne {
	return _u.SetEntityID(v.ID)
}

// Mutation returns the EntityPriceHistoryMutation object of the builder.
func (_u *EntityPriceHistoryUpdateOne) Mutation() *EntityPriceHistoryMutation {
	return _u.mutation
}

// ClearEntity clears the "entity" edge to the Entity entity.
func (_u *EntityPriceHistoryUpdateOne) ClearEntity() *EntityPriceHistoryUpdateOne {
	_u.mutation.ClearEntity()
	return _u
}

// Where appends a list predicates to the EntityPriceHistoryUpdate builder.
func (_u *EntityPriceHistoryUpdateOne) Where(ps ...predicate.EntityPriceHistory) *EntityPriceHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntityPriceHistoryUpdateOne) Select(field string, fields ...string) *EntityPriceHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EntityPriceHistory entity.
func (_u *EntityPriceHistoryUpdateOne) Save(ctx context.Context) (*EntityPriceHistory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntityPriceHistoryUpdateOne) SaveX(ctx context.Context) *EntityPriceHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntityPriceHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntityPriceHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntityPriceHistoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entitypricehistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntityPriceHistoryUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := entitypricehistory.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "EntityPriceHistory.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceID(); ok {
		if err := entitypricehistory.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "EntityPriceHistory.source_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Notes(); ok {
		if err := entitypricehistory.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "EntityPriceHistory.notes": %w`, err)}
		}
	}
	if _u.mutation.EntityCleared() && len(_u.mutation.EntityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityPriceHistory.entity"`)
	}
	return nil
}

func (_u *EntityPriceHistoryUpdateOne) sqlSave(ctx context.Context) (_node *EntityPriceHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entitypricehistory.Table, entitypricehistory.Columns, sqlgraph.NewFieldSpec(entitypricehistory.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EntityPriceHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entitypricehistory.FieldID)
		for _, f := range fields {
			if !entitypricehistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entitypricehistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entitypricehistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(entitypricehistory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(entitypricehistory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MarketLow(); ok {
		_spec.SetField(entitypricehistory.FieldMarketLow, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMarketLow(); ok {
		_spec.AddField(entitypricehistory.FieldMarketLow, field.TypeFloat64, value)
	}
	if _u.mutation.MarketLowCleared() {
		_spec.ClearField(entitypricehistory.FieldMarketLow, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MarketMid(); ok {
		_spec.SetField(entitypricehistory.FieldMarketMid, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMarketMid(); ok {
		_spec.AddField(entitypricehistory.FieldMarketMid, field.TypeFloat64, value)
	}
	if _u.mutation.MarketMidCleared() {
		_spec.ClearField(entitypricehistory.FieldMarketMid, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MarketHigh(); ok {
		_spec.SetField(entitypricehistory.FieldMarketHigh, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMarketHigh(); ok {
		_spec.AddField(entitypricehistory.FieldMarketHigh, field.TypeFloat64, value)
	}
	if _u.mutation.MarketHighCleared() {
		_spec.ClearField(entitypricehistory.FieldMarketHigh, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DirectLow(); ok {
		_spec.SetField(entitypricehistory.FieldDirectLow, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDirectLow(); ok {
		_spec.AddField(entitypricehistory.FieldDirectLow, field.TypeFloat64, value)
	}
	if _u.mutation.DirectLowCleared() {
		_spec.ClearField(entitypricehistory.FieldDirectLow, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(entitypricehistory.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(entitypricehistory.FieldSourceID, field.TypeString, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(entitypricehistory.FieldSourceID, field.TypeString)
	}
	if value, ok := _u.mutation.RecordedAt(); ok {
		_spec.SetField(entitypricehistory.FieldRecordedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(entitypricehistory.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(entitypricehistory.FieldNotes, field.TypeString)
	}
	if _u.mutation.EntityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitypricehistory.EntityTable,
			Columns: []string{entitypricehistory.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitypricehistory.EntityTable,
			Columns: []string{entitypricehistory.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EntityPriceHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitypricehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
