// Code generated by ent, DO NOT EDIT.

package entitypricehistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the entitypricehistory type in the database.
	Label = "entity_price_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldMarketLow holds the string denoting the market_low field in the database.
	FieldMarketLow = "market_low"
	// FieldMarketMid holds the string denoting the market_mid field in the database.
	FieldMarketMid = "market_mid"
	// FieldMarketHigh holds the string denoting the market_high field in the database.
	FieldMarketHigh = "market_high"
	// FieldDirectLow holds the string denoting the direct_low field in the database.
	FieldDirectLow = "direct_low"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldRecordedAt holds the string denoting the recorded_at field in the database.
	FieldRecordedAt = "recorded_at"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgeEntity holds the string denoting the entity edge name in mutations.
	EdgeEntity = "entity"
	// Table holds the table name of the entitypricehistory in the database.
	Table = "entity_price_histories"
	// EntityTable is the table that holds the entity relation/edge.
	EntityTable = "entity_price_histories"
	// EntityInverseTable is the table name for the Entity entity.
	// It exists in this package in order to avoid circular dependency with the "entity" package.
	EntityInverseTable = "entities"
	// EntityColumn is the table column denoting the entity relation/edge.
	EntityColumn = "entity_id"
)

// Columns holds all SQL columns for entitypricehistory fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldEntityID,
	FieldPrice,
	FieldMarketLow,
	FieldMarketMid,
	FieldMarketHigh,
	FieldDirectLow,
	FieldSource,
	FieldSourceID,
	FieldRecordedAt,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultPrice holds the default value on creation for the "price" field.
	DefaultPrice float64
	// DefaultMarketLow holds the default value on creation for the "market_low" field.
	DefaultMarketLow float64
	// DefaultMarketMid holds the default value on creation for the "market_mid" field.
	DefaultMarketMid float64
	// DefaultMarketHigh holds the default value on creation for the "market_high" field.
	DefaultMarketHigh float64
	// DefaultDirectLow holds the default value on creation for the "direct_low" field.
	DefaultDirectLow float64
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// SourceIDValidator is a validator for the "source_id" field. It is called by the builders before save.
	SourceIDValidator func(string) error
	// NotesValidator is a validator for the "notes" field. It is called by the builders before save.
	NotesValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the EntityPriceHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByMarketLow orders the results by the market_low field.
func ByMarketLow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMarketLow, opts...).ToFunc()
}

// ByMarketMid orders the results by the market_mid field.
func ByMarketMid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMarketMid, opts...).ToFunc()
}

// ByMarketHigh orders the results by the market_high field.
func ByMarketHigh(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMarketHigh, opts...).ToFunc()
}

// ByDirectLow orders the results by the direct_low field.
func ByDirectLow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirectLow, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// ByRecordedAt orders the results by the recorded_at field.
func ByRecordedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordedAt, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByEntityField orders the results by entity field.
func ByEntityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntityStep(), sql.OrderByField(field, opts...))
	}
}
func newEntityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EntityTable, EntityColumn),
	)
}
