// Code generated by ent, DO NOT EDIT.

package entitypricehistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v uuid.UUID) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldEntityID, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldPrice, v))
}

// MarketLow applies equality check predicate on the "market_low" field. It's identical to MarketLowEQ.
func MarketLow(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldMarketLow, v))
}

// MarketMid applies equality check predicate on the "market_mid" field. It's identical to MarketMidEQ.
func MarketMid(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldMarketMid, v))
}

// MarketHigh applies equality check predicate on the "market_high" field. It's identical to MarketHighEQ.
func MarketHigh(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldMarketHigh, v))
}

// DirectLow applies equality check predicate on the "direct_low" field. It's identical to DirectLowEQ.
func DirectLow(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldDirectLow, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldSource, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldSourceID, v))
}

// RecordedAt applies equality check predicate on the "recorded_at" field. It's identical to RecordedAtEQ.
func RecordedAt(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldRecordedAt, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLTE(FieldUpdatedAt, v))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v uuid.UUID) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v uuid.UUID) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...uuid.UUID) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...uuid.UUID) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotIn(FieldEntityID, vs...))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLTE(FieldPrice, v))
}

// MarketLowEQ applies the EQ predicate on the "market_low" field.
func MarketLowEQ(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldMarketLow, v))
}

// MarketLowNEQ applies the NEQ predicate on the "market_low" field.
func MarketLowNEQ(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNEQ(FieldMarketLow, v))
}

// MarketLowIn applies the In predicate on the "market_low" field.
func MarketLowIn(vs ...float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIn(FieldMarketLow, vs...))
}

// MarketLowNotIn applies the NotIn predicate on the "market_low" field.
func MarketLowNotIn(vs ...float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotIn(FieldMarketLow, vs...))
}

// MarketLowGT applies the GT predicate on the "market_low" field.
func MarketLowGT(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGT(FieldMarketLow, v))
}

// MarketLowGTE applies the GTE predicate on the "market_low" field.
func MarketLowGTE(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGTE(FieldMarketLow, v))
}

// MarketLowLT applies the LT predicate on the "market_low" field.
func MarketLowLT(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLT(FieldMarketLow, v))
}

// MarketLowLTE applies the LTE predicate on the "market_low" field.
func MarketLowLTE(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLTE(FieldMarketLow, v))
}

// MarketLowIsNil applies the IsNil predicate on the "market_low" field.
func MarketLowIsNil() predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIsNull(FieldMarketLow))
}

// MarketLowNotNil applies the NotNil predicate on the "market_low" field.
func MarketLowNotNil() predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotNull(FieldMarketLow))
}

// MarketMidEQ applies the EQ predicate on the "market_mid" field.
func MarketMidEQ(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldMarketMid, v))
}

// MarketMidNEQ applies the NEQ predicate on the "market_mid" field.
func MarketMidNEQ(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNEQ(FieldMarketMid, v))
}

// MarketMidIn applies the In predicate on the "market_mid" field.
func MarketMidIn(vs ...float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIn(FieldMarketMid, vs...))
}

// MarketMidNotIn applies the NotIn predicate on the "market_mid" field.
func MarketMidNotIn(vs ...float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotIn(FieldMarketMid, vs...))
}

// MarketMidGT applies the GT predicate on the "market_mid" field.
func MarketMidGT(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGT(FieldMarketMid, v))
}

// MarketMidGTE applies the GTE predicate on the "market_mid" field.
func MarketMidGTE(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGTE(FieldMarketMid, v))
}

// MarketMidLT applies the LT predicate on the "market_mid" field.
func MarketMidLT(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLT(FieldMarketMid, v))
}

// MarketMidLTE applies the LTE predicate on the "market_mid" field.
func MarketMidLTE(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLTE(FieldMarketMid, v))
}

// MarketMidIsNil applies the IsNil predicate on the "market_mid" field.
func MarketMidIsNil() predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIsNull(FieldMarketMid))
}

// MarketMidNotNil applies the NotNil predicate on the "market_mid" field.
func MarketMidNotNil() predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotNull(FieldMarketMid))
}

// MarketHighEQ applies the EQ predicate on the "market_high" field.
func MarketHighEQ(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldMarketHigh, v))
}

// MarketHighNEQ applies the NEQ predicate on the "market_high" field.
func MarketHighNEQ(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNEQ(FieldMarketHigh, v))
}

// MarketHighIn applies the In predicate on the "market_high" field.
func MarketHighIn(vs ...float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIn(FieldMarketHigh, vs...))
}

// MarketHighNotIn applies the NotIn predicate on the "market_high" field.
func MarketHighNotIn(vs ...float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotIn(FieldMarketHigh, vs...))
}

// MarketHighGT applies the GT predicate on the "market_high" field.
func MarketHighGT(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGT(FieldMarketHigh, v))
}

// MarketHighGTE applies the GTE predicate on the "market_high" field.
func MarketHighGTE(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGTE(FieldMarketHigh, v))
}

// MarketHighLT applies the LT predicate on the "market_high" field.
func MarketHighLT(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLT(FieldMarketHigh, v))
}

// MarketHighLTE applies the LTE predicate on the "market_high" field.
func MarketHighLTE(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLTE(FieldMarketHigh, v))
}

// MarketHighIsNil applies the IsNil predicate on the "market_high" field.
func MarketHighIsNil() predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIsNull(FieldMarketHigh))
}

// MarketHighNotNil applies the NotNil predicate on the "market_high" field.
func MarketHighNotNil() predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotNull(FieldMarketHigh))
}

// DirectLowEQ applies the EQ predicate on the "direct_low" field.
func DirectLowEQ(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldDirectLow, v))
}

// DirectLowNEQ applies the NEQ predicate on the "direct_low" field.
func DirectLowNEQ(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNEQ(FieldDirectLow, v))
}

// DirectLowIn applies the In predicate on the "direct_low" field.
func DirectLowIn(vs ...float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIn(FieldDirectLow, vs...))
}

// DirectLowNotIn applies the NotIn predicate on the "direct_low" field.
func DirectLowNotIn(vs ...float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotIn(FieldDirectLow, vs...))
}

// DirectLowGT applies the GT predicate on the "direct_low" field.
func DirectLowGT(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGT(FieldDirectLow, v))
}

// DirectLowGTE applies the GTE predicate on the "direct_low" field.
func DirectLowGTE(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGTE(FieldDirectLow, v))
}

// DirectLowLT applies the LT predicate on the "direct_low" field.
func DirectLowLT(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLT(FieldDirectLow, v))
}

// DirectLowLTE applies the LTE predicate on the "direct_low" field.
func DirectLowLTE(v float64) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLTE(FieldDirectLow, v))
}

// DirectLowIsNil applies the IsNil predicate on the "direct_low" field.
func DirectLowIsNil() predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIsNull(FieldDirectLow))
}

// DirectLowNotNil applies the NotNil predicate on the "direct_low" field.
func DirectLowNotNil() predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotNull(FieldDirectLow))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldContainsFold(FieldSource, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDContains applies the Contains predicate on the "source_id" field.
func SourceIDContains(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldContains(FieldSourceID, v))
}

// SourceIDHasPrefix applies the HasPrefix predicate on the "source_id" field.
func SourceIDHasPrefix(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldHasPrefix(FieldSourceID, v))
}

// SourceIDHasSuffix applies the HasSuffix predicate on the "source_id" field.
func SourceIDHasSuffix(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldHasSuffix(FieldSourceID, v))
}

// SourceIDIsNil applies the IsNil predicate on the "source_id" field.
func SourceIDIsNil() predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIsNull(FieldSourceID))
}

// SourceIDNotNil applies the NotNil predicate on the "source_id" field.
func SourceIDNotNil() predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotNull(FieldSourceID))
}

// SourceIDEqualFold applies the EqualFold predicate on the "source_id" field.
func SourceIDEqualFold(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEqualFold(FieldSourceID, v))
}

// SourceIDContainsFold applies the ContainsFold predicate on the "source_id" field.
func SourceIDContainsFold(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldContainsFold(FieldSourceID, v))
}

// RecordedAtEQ applies the EQ predicate on the "recorded_at" field.
func RecordedAtEQ(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldRecordedAt, v))
}

// RecordedAtNEQ applies the NEQ predicate on the "recorded_at" field.
func RecordedAtNEQ(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNEQ(FieldRecordedAt, v))
}

// RecordedAtIn applies the In predicate on the "recorded_at" field.
func RecordedAtIn(vs ...time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIn(FieldRecordedAt, vs...))
}

// RecordedAtNotIn applies the NotIn predicate on the "recorded_at" field.
func RecordedAtNotIn(vs ...time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotIn(FieldRecordedAt, vs...))
}

// RecordedAtGT applies the GT predicate on the "recorded_at" field.
func RecordedAtGT(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGT(FieldRecordedAt, v))
}

// RecordedAtGTE applies the GTE predicate on the "recorded_at" field.
func RecordedAtGTE(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGTE(FieldRecordedAt, v))
}

// RecordedAtLT applies the LT predicate on the "recorded_at" field.
func RecordedAtLT(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLT(FieldRecordedAt, v))
}

// RecordedAtLTE applies the LTE predicate on the "recorded_at" field.
func RecordedAtLTE(v time.Time) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLTE(FieldRecordedAt, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.FieldContainsFold(FieldNotes, v))
}

// HasEntity applies the HasEdge predicate on the "entity" edge.
func HasEntity() predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EntityTable, EntityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntityWith applies the HasEdge predicate on the "entity" edge with a given conditions (other predicates).
func HasEntityWith(preds ...predicate.Entity) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(func(s *sql.Selector) {
		step := newEntityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EntityPriceHistory) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EntityPriceHistory) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EntityPriceHistory) predicate.EntityPriceHistory {
	return predicate.EntityPriceHistory(sql.NotPredicates(p))
}
